# Regressions to get most significant words for each dimension

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression


from sklearn.feature_selection import f_regression
from sklearn.preprocessing import StandardScaler

In [2]:
Scaler = StandardScaler()
sns.set ()

## Import data from previous processing

In [3]:
raw_data = pd.read_csv('Data for Clustering - Count.txt')
raw_data.drop('Partido', axis = 1, inplace=True)
raw_data

,abandono escolar,acesso,administração pública,animal,apoio,atingir objetivos desenvolvimento,através,aumento,bem,bem estar,...,sobre,social,socialismo,também,tem,todo,trabalhar,é,é essencial,é necessário
0,4.0,101.0,14.0,42.0,111.0,0.0,68.0,102.0,60.0,11.0,...,133.0,242.0,0.0,78.0,152.0,160.0,155.0,338.0,2.0,17.0
1,0.0,2.0,0.0,0.0,8.0,0.0,1.0,4.0,3.0,2.0,...,5.0,12.0,0.0,3.0,3.0,15.0,3.0,11.0,1.0,0.0
2,0.0,5.0,0.0,0.0,3.0,0.0,5.0,5.0,8.0,0.0,...,4.0,37.0,17.0,1.0,1.0,6.0,3.0,13.0,0.0,0.0
3,54.0,326.0,113.0,45.0,166.0,0.0,188.0,240.0,223.0,20.0,...,359.0,339.0,3.0,298.0,503.0,407.0,205.0,1161.0,57.0,74.0
4,0.0,70.0,16.0,50.0,66.0,0.0,118.0,28.0,77.0,36.0,...,62.0,129.0,1.0,39.0,37.0,156.0,96.0,81.0,3.0,12.0
5,3.0,82.0,18.0,290.0,105.0,31.0,78.0,63.0,137.0,67.0,...,83.0,119.0,0.0,54.0,99.0,247.0,85.0,185.0,11.0,16.0
6,2.0,65.0,32.0,0.0,90.0,0.0,103.0,74.0,57.0,0.0,...,46.0,170.0,0.0,43.0,113.0,97.0,58.0,283.0,5.0,15.0
7,1.0,103.0,62.0,4.0,180.0,0.0,157.0,86.0,74.0,8.0,...,51.0,199.0,0.0,75.0,37.0,159.0,112.0,136.0,11.0,8.0
8,1.0,69.0,42.0,11.0,119.0,0.0,122.0,83.0,154.0,17.0,...,67.0,236.0,0.0,132.0,181.0,149.0,73.0,394.0,6.0,28.0

In [4]:
DataMDS = pd.read_csv('MDS Data.txt')
DataMDS.drop('Unnamed: 0', axis = 1, inplace=True)
DataMDS

,Partido,1Dimension1,2Dimension1,2Dimension2,3Dimension1,3Dimension2,3Dimension3,4Dimension1,4Dimension2,4Dimension3,4Dimension4
0,BE,0.064726,0.057276,-0.096712,-895.167889,8690.630366,6974.494075,-0.003525,-0.059650,-0.064949,-0.015520
1,CDS,-0.330618,0.010963,0.369108,-21748.646868,-24584.955206,-21650.498041,-0.093135,0.206793,0.215235,-0.184562
2,CH,-0.442637,-0.266675,0.293324,12423.071853,-19940.809108,-36727.827669,0.132037,0.368821,0.016234,-0.034134
3,IL,0.675479,-0.081888,-0.660486,22309.298269,21077.916895,64763.330566,0.296591,-0.540427,-0.237750,0.013136
4,Livre,-0.142668,0.161851,0.147569,-11377.765245,11427.216158,-17343.109688,-0.132713,0.133431,-0.003964,0.122649
5,PAN,-0.036921,0.160517,-0.017143,-13853.976043,3831.528812,3316.418428,-0.115766,0.010342,-0.081534,-0.032263
6,PCP,0.007648,-0.045105,0.018142,1568.490580,-6705.582124,-520.926613,-0.001859,0.002227,0.086672,0.042518
7,PS,0.080529,0.049613,0.012927,5843.608001,7906.655391,-5441.844638,-0.108669,-0.055923,0.042154,0.030835
8,PSD,0.124462,-0.046552,-0.066729,5731.087342,-1702.601185,6629.963581,0.027038,-0.065614,0.027903,0.057340

In [5]:
OutputLinearRegression = pd.DataFrame(columns = DataMDS.columns)
OutputLinearRegression.drop('Partido', axis = 1, inplace=True)
OutputLinearRegression['Words'] = raw_data.columns
OutputLinearRegression

,1Dimension1,2Dimension1,2Dimension2,3Dimension1,3Dimension2,3Dimension3,4Dimension1,4Dimension2,4Dimension3,4Dimension4,Words
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,abandono escolar
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,acesso
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,administração pública
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,animal
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apoio
...,...,...,...,...,...,...,...,...,...,...,...
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,todo
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trabalhar
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,é
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,é essencial
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,é necessário

## Execute Regression

In [6]:
x = raw_data

for i in range(10):
    y = DataMDS[DataMDS.columns[i+1]]
    reg = LinearRegression(fit_intercept=False)
    reg.fit(x,y)
    OutputLinearRegression[DataMDS.columns[i+1]] = reg.coef_

## Print Regression Results

In [7]:
for i in range(10):
    print([DataMDS.columns[i+1]])
    ToPrint = OutputLinearRegression[['Words', DataMDS.columns[i+1]]].sort_values(by=DataMDS.columns[i+1],ascending=True)
    ToPrint = ToPrint.sort_values(by=DataMDS.columns[i+1],ascending=True)
    print(ToPrint)
    #print(OutputLinearRegression[['Words', DataMDS.columns[i+1]]])
    print("\n")

['1Dimension1']
           Words  1Dimension1
16   compromisso    -0.003568
29       direita    -0.002434
42        estado    -0.002393
15      combater    -0.001448
114       social    -0.001436
..           ...          ...
116       também     0.000965
65          novo     0.001099
117          tem     0.001133
120            é     0.001347
87      programa     0.001661

[123 rows x 2 columns]


['2Dimension1']
               Words  2Dimension1
29           direita    -0.001742
19            contra    -0.000986
114           social    -0.000924
115       socialismo    -0.000864
84         princípio    -0.000753
..               ...          ...
26   desenvolvimento     0.000422
35           empresa     0.000463
58           medidas     0.000544
21             criar     0.000568
16       compromisso     0.000677

[123 rows x 2 columns]


['2Dimension2']
           Words  2Dimension2
87      programa    -0.001520
120            é    -0.001254
117          tem    -0.000977
65          novo    -0.000927
57          mais    -0.000912
..           ...          ...
55     liberdade     0.001407
15      combater     0.001485
58       medidas     0.001659
42        estado     0.002478
16   compromisso     0.004379

[123 rows x 2 columns]


['3Dimension1']
           Words  3Dimension1
16   compromisso  -318.928465
58       medidas  -149.860459
42        estado  -114.245102
35       empresa   -95.202672
118         todo   -78.122473
..           ...          ...
84     princípio    58.115129
19        contra    60.110834
100        saúde    64.316837
115   socialismo    66.545381
29       direita   109.687807

[123 rows x 2 columns]


['3Dimension2']
           Words  3Dimension2
16   compromisso  -293.040520
42        estado  -165.490711
58       medidas  -109.267494
29       direita   -95.072115
15      combater   -94.780726
..           ...          ...
117          tem    58.177200
65          novo    62.120967
89      proposta    65.156197
120            é    68.841881
87      programa   105.542944

[123 rows x 2 columns]


['3Dimension3']
           Words  3Dimension3
16   compromisso  -216.937772
29       direita  -206.747399
42        estado  -164.185088
114       social  -123.780282
19        contra  -120.092019
..           ...          ...
116       também    72.699650
65          novo    78.295738
117          tem    90.729289
120            é   106.573696
87      programa   113.688457

[123 rows x 2 columns]


['4Dimension1']
           Words  4Dimension1
16   compromisso    -0.001513
58       medidas    -0.000803
35       empresa    -0.000557
118         todo    -0.000453
50      garantia    -0.000392
..           ...          ...
84     princípio     0.000464
114       social     0.000487
115   socialismo     0.000543
19        contra     0.000558
29       direita     0.000999

[123 rows x 2 columns]


['4Dimension2']
           Words  4Dimension2
87      programa    -0.001154
120            é    -0.000968
117          tem    -0.000841
65          novo    -0.000809
116       também    -0.000716
..           ...          ...
19        contra     0.001227
114       social     0.001238
42        estado     0.001587
16   compromisso     0.002052
29       direita     0.002101

[123 rows x 2 columns]


['4Dimension3']
           Words  4Dimension3
87      programa    -0.000741
100        saúde    -0.000542
120            é    -0.000498
76       pessoas    -0.000498
73         outro    -0.000459
..           ...          ...
55     liberdade     0.000765
35       empresa     0.000799
58       medidas     0.001233
42        estado     0.001288
16   compromisso     0.002872

[123 rows x 2 columns]


['4Dimension4']
          Words  4Dimension4
16  compromisso    -0.002411
42       estado    -0.001139
58      medidas    -0.000964
15     combater    -0.000680
55    liberdade    -0.000634
..          ...          ...
68        nível     0.000392
6       através     0.000454
57         mais     0.000481
87     programa     0.000519
89     proposta     0.000660

[123 rows x 2 columns]